### ISSUE TITLE
Downloading and running

### ISSUE THREAD

**Issue by GNz-11** [Calteo/Slooh.Explorer#1]
Hey Calteo, a slooh member and ambassador here. I was using this explorer (1.0.39) when it was publicly released in april of 2021, it was a great software and it made it a lot easier to download bulk images from missions. I reinstalled windows on my pc and the exlporer got deleted in that process. I again downloaded in march of this year but was facing a lot of lag in the explorer (1.0.42) so stopped using it. Today I came to check for updates and version 1.0.46 is available. How can I install and run it because every downloadable link is giving me the source code file instead of the explorer file which was in version 1.0.42? 

Good luck developing this!
Yajvin

**Comment by Calteo** [comment]
Hello Yajvin,

 

the explorer can be installed an updated via chocolately (https://chocolatey.org/).

Link to the package is https://community.chocolatey.org/packages/slooh-explorer

 

Sorry to hear that it has some lags.

But I I not using an official API from slooh. Just doing the same things that the web site is doing. Fortunately slooh uses some REST services that are self-explanatory.

 

I do not know how their site behaves on large image/mission counts. I would like to have an official API and some more performant operations, but I guess this is not the main focus of their site.

 

I should include a zip on github releases that contain the binaries – though.

 

Regards,

Matthias

 

Von: GNz-11 ***@***.***> 
Gesendet: Freitag, 10. Juni 2022 16:04
An: Calteo/Slooh.Explorer ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Calteo/Slooh.Explorer] Downloading and running (Issue #1)

 

Hey Calteo, a slooh member and ambassador here. I was using this explorer (1.0.39) when it was publicly released in april of 2021, it was a great software and it made it a lot easier to download bulk images from missions. I reinstalled windows on my pc and the exlporer got deleted in that process. I again downloaded in march of this year but was facing a lot of lag in the explorer (1.0.42) so stopped using it. Today I came to check for updates and version 1.0.46 is available. How can I install and run it because every downloadable link is giving me the source code file instead of the explorer file which was in version 1.0.42?

Good luck developing this!
Yajvin

**Comment by geekster123** [comment]
I did all of the above and all went OK. However when I run Slooh.Explorer as Admin I get error message;
"The SSL connection could not be established, see inner exception"
If I just run it the normal way I get error message;
"An error occured while sending the request"
I was getting the same error message using the old version 1.0.42.
I am running Win 10 Pro x64, .Net Runtime 6.0.6.
I love this program and it always ran correctly for me until now. As I have 100's of FITS to download from Slooh I would really like to get this working again.
What gives?

**Comment by GNz-11** [comment]
> I did all of the above and all went OK. However when I run Slooh.Explorer as Admin I get error message; "The SSL connection could not be established, see inner exception" If I just run it the normal way I get error message; "An error occured while sending the request" I was getting the same error message using the old version 1.0.42. I am running Win 10 Pro x64, .Net Runtime 6.0.6. I love this program and it always ran correctly for me until now. As I have 100's of FITS to download from Slooh I would really like to get this working again. What gives?

Hey Geekster. After Slooh changed its website URL from slooh.com to app.slooh.com , this software is not able to connect to the new website. I'm also facing the same issue. Waiting for Matthias to fix this issue in the next release

**Comment by geekster123** [comment]
Are you sure that is the problem? I do hope this gets fixed fast. I would pay for this software it is so useful to me.

**Comment by Calteo** [comment]
I got some information from slooh, but I will only be able to look into this next week. Hopefully it will solve the problem.

**Comment by Calteo** [comment]
I have updated the slooh url and the version 1.0.47 is now functioning again. 
It will show up at chocolately soon - I hope.
I will redo the build so we get a zip file here also.

Hope this helps.
