### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by epraton** [Calteo/Slooh.Explorer#2]
Hi Matthias,

I have been using Slooh Explorer for the past few weeks to download images from my Slooh archive, but late last week the app suddenly stopped being able to connect to Slooh.

Starting the afternoon of 2022 June 23, when I click the Logon button after entering my Slooh user name and password in the Slooh Explorer dialog box, I get a message 

	“An error occurred while sending the request.”

If I try again, the message changes to 

	“The SSL connection could not be established, see inner exception.”

I am using  v. 1.0.46, installed from the [Chocolatey Community archive](https://community.chocolatey.org/packages?q=slooh)), but the same thing happens if I try any of the earlier versions (all previously working), or a different PC, etc.

A fellow Slooh member suggested that the issue is caused by a change at Slooh that happened around then, where a login takes you to [app.slooh.com](https://app.slooh.com/login) instead of [slooh.com](https://www.slooh.com/).  

*  If the change in login is indeed the problem (as seems likely), is it possible to fix the app so that it can again connect, if that is an easy fix, and also post the update to the Chocolatey archive?

Thanks so much for generously sharing this app.  

-- Elizabeth

**Comment by Calteo** [comment]
I have updated the slooh url and the version 1.0.47 is now functioning again. 
It will show up at chocolately soon - I hope.
I will redo the build so we get a zip file here also.

Hope this helps.

**Comment by Calteo** [comment]
Hi Elizabeth,

 

I am facing the same issue. I will have to investigate that.

 

The reason behind this is that I do not have an official interface from slooh. The program just uses the same requests that the web site from slooh is using.

So if they change their coding it breaks the application. Maybe I can convince the slooh operators to provide an stable interface that an application can access.

 

Unfortunately this will not happen soon I guess.

 

Regards,

Matthias

 

Von: epraton ***@***.***> 
Gesendet: Dienstag, 28. Juni 2022 23:19
An: Calteo/Slooh.Explorer ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [Calteo/Slooh.Explorer] Connection Issue (Issue #2)

 

Hi Matthias,

I have been using Slooh Explorer for the past few weeks to download images from my Slooh archive, but late last week the app suddenly stopped being able to connect to Slooh.

Starting the afternoon of 2022 June 23, when I click the Logon button after entering my Slooh user name and password in the Slooh Explorer dialog box, I get a message

“An error occurred while sending the request.”
 

If I try again, the message changes to

“The SSL connection could not be established, see inner exception.”
 

I am using v. 1.0.46, installed from the Chocolatey Community archive <https://community.chocolatey.org/packages?q=slooh> ), but the same thing happens if I try any of the earlier versions (all previously working), or a different PC, etc.

A fellow Slooh member suggested that the issue is caused by a change at Slooh that happened around then, where a login takes you to app.slooh.com <https://app.slooh.com/login>  instead of slooh.com <https://www.slooh.com/> .

*	If the change in login is indeed the problem (as seems likely), is it possible to fix the app so that it can again connect, if that is an easy fix, and also post the update to the Chocolatey archive?

Thanks so much for generously sharing this app.

-- Elizabeth
